---
- name: Installation of Regolith workstation environment
  hosts: all
  become: no
  vars:
    packages:
      apt:
      - apt-utils
      - unzip
      - bison
      - cmake
      - curl
      - exa
      - git
      - gzip
      - i3xrocks-info
      - i3xrocks-memory
      - i3xrocks-rofication
      - libconfig++-dev
      - libevdev-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libudev-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - neofetch
      - neovim
      - pkg-config
      - regolith-system-ubuntu
      - tmux
      - zoxide
      - zsh
  tasks:
    - name: Register Regolith public key and repository
      become: yes
      shell: |
        wget -qO - https://regolith-desktop.org/regolith.key | \
          gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
        echo deb "[arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] \
          https://regolith-desktop.org/release-ubuntu-jammy-amd64 jammy main" | \
          sudo tee /etc/apt/sources.list.d/regolith.list

    - name: Install apt packages
      become: yes
      apt:
        name: "{{ packages.apt }}"
        state: latest
        update_cache: yes
        install_recommends: yes

    - name: Download FiraCode font
      get_url:
        url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/FiraCode.zip
        dest: /tmp/FiraCode.zip
        mode: 0755

    - name: Install FiraCode font
      shell: |
        unzip /tmp/FiraCode.zip -d /usr/share/fonts
        fc-cache -fv

    - name: Change user shell to zsh
      become: yes
      user:
        name: vagrant
        shell: /usr/bin/zsh
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_file: .ssh/id_ed25519

    - name: Install oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        depth: 1

    - name: Install starship prompt
      become: yes
      snap:
        name: starship

    - name: Remove useless packages from the cache
      become: yes
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes
